
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml

sensor: !include_dir_merge_list includes/sensors
template: !include_dir_merge_list includes/template
binary_sensor: !include_dir_merge_list includes/bin_sensor

recorder: !include includes/recorder.yaml
counter: !include includes/counter.yaml
mqtt: !include includes/mqtt.yaml
input_button: !include includes/input_button.yaml
command_line: !include includes/command_line.yaml
input_number: !include includes/input_number.yaml
input_boolean: !include includes/input_boolean.yaml
input_text: !include includes/input_text.yaml


panel_custom:
  - name: hassio_system
    sidebar_title: 'System'
    sidebar_icon: mdi:wrench-outline
    js_url: /api/hassio/app/entrypoint.js
    url_path: 'hassio/system'
    embed_iframe: true
    require_admin: true
    config:
      ingress: core_configurator

telegram_bot:
#  - proxy_url: socks5://proxy_address:port
#    proxy_params:
#      username: proxy_user
#      password: proxy_password
  - platform: polling
    api_key: !secret telegram_token
    allowed_chat_ids:
      - !secret my_chat_id
      - !secret dima_chat_id
      
notify:
  - platform: telegram
    name: "tlg_my"
    chat_id: !secret my_chat_id
  - platform: telegram
    name: "tlg_dima"
    chat_id: !secret dima_chat_id
      

python_script:
  requirements:
  - requests
  
influxdb:
  host: localhost
  port: 8086
  database: homeassistant
  username: homeassistant
  password: homeassistant
  max_retries: 3
  default_measurement: state

http:

homeassistant:
  customize: !include includes/customize.yaml

# lovelace:
#   mode: yaml
#   resources:
#     - url: /hacsfiles/battery-state-card/battery-state-card.js
#       type: module
#     - url: /hacsfiles/lovelace-multiple-entity-row/multiple-entity-row.js
#       type: module
#     - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
#       type: module
#     - url: /hacsfiles/clock-weather-card/clock-weather-card.js
#       type: module
#     - url: /hacsfiles/stack-in-card/stack-in-card.js
#       type: module
#     - url: /hacsfiles/lovelace-auto-entities/auto-entities.js
#       type: module
#     - url: /hacsfiles/button-card/button-card.js
#       type: module
#     - url: /hacsfiles/lovelace-template-entity-row/template-entity-row.js
#       type: module
#     - url: /hacsfiles/vertical-stack-in-card/vertical-stack-in-card.js
#       type: module
      
#   dashboards:
#     lovelace-lc:
#       mode: yaml
#       filename: ui-lc_hub.yaml
#       title: LC Hub
#       icon: mdi:application-settings-outline
#       show_in_sidebar: true