
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

automation: !include_dir_merge_list includes/automation
script: !include_dir_merge_named includes/scripts
sensor: !include_dir_merge_list includes/sensors
template: !include_dir_merge_list includes/template
binary_sensor: !include_dir_merge_list includes/bin_sensor

recorder: !include includes/recorder.yaml
counter: !include includes/counter.yaml
mqtt: !include includes/mqtt.yaml


panel_custom:
  - name: hassio_system
    sidebar_title: 'System'
    sidebar_icon: mdi:wrench-outline
    js_url: /api/hassio/app/entrypoint.js
    url_path: 'hassio/system'
    embed_iframe: true
    require_admin: true
    config:
      ingress: core_configurator

telegram_bot:
#  - proxy_url: socks5://proxy_address:port
#    proxy_params:
#      username: proxy_user
#      password: proxy_password
  - platform: polling
    api_key: !secret telegram_token
    allowed_chat_ids:
      - !secret my_chat_id
      

python_script:
  requirements:
  - requests


lovelace:
  mode: yaml
  resources:
    - url: /hacsfiles/battery-state-card/battery-state-card.js
      type: module
    - url: /hacsfiles/flex-table-card/flex-table-card.js
      type: module
    - url: /hacsfiles/lovelace-multiple-entity-row/multiple-entity-row.js
      type: module
    - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
      type: module
    - url: /hacsfiles/clock-weather-card/clock-weather-card.js
      type: module
    - url: /hacsfiles/stack-in-card/stack-in-card.js
      type: module
    - url: /hacsfiles/lovelace-auto-entities/auto-entities.js
      type: module