- platform: integration
  source: sensor.current_power
  unit_prefix: k
  unit_time: h
  name: current_power_integration

- platform: integration
  source: sensor.0xa4c138d7adc79f6a_power
  unit_prefix: k
  unit_time: h
  name: 0xa4c138d7adc79f6a_integration
    
- platform: integration
  source: sensor.212a01_5448e6d89786_power
  unit_prefix: k
  unit_time: h
  name: 212a01_5448e6d89786_integration
    
- platform: integration
  source: sensor.212a01_5448e6e68e77_power
  unit_prefix: k
  unit_time: h
  name: 212a01_5448e6e68e77_integration