sensor:
    ## Пылесос ##
  - name: "vacuum state"
    state_topic: "vacuum/state"
    
    ## Ноут ##    

  - name: "laptop cpu"
    state_topic: "lap/cpu"    
  - name: "laptop memory use percent"
    state_topic: "lap/mem"
  - name: "laptop disk C used"
    state_topic: "lap/DC/used"
  - name: "laptop disk C free"
    state_topic: "lap/DC/free"
  - name: "laptop disk D used"
    state_topic: "lap/DD/used"
  - name: "laptop disk D free"
    state_topic: "lap/DD/free"
  - name: "laptop disk E used"
    state_topic: "lap/DE/used"
  - name: "laptop disk E free"
    state_topic: "lap/DE/free"
  - name: "laptop disk F used"
    state_topic: "lap/DF/used" 
  - name: "laptop disk F free"
    state_topic: "lap/DF/free"

    ## ПК ##    
  
  - name: "pc cpu"
    state_topic: "pc/cpu"    
  - name: "pc memory use percent"
    state_topic: "pc/mem"
  - name: "pc disk C used"
    state_topic: "pc/DC/used"
  - name: "pc disk C free"
    state_topic: "pc/DC/free"
  - name: "pc disk D used"
    state_topic: "pc/DD/used"
  - name: "pc disk D free"
    state_topic: "pc/DD/free"
    
              
    ## Роутер ##
  - name: "router uptime"
    state_topic: "router/uptime"    
  - name: "router memory"
    state_topic: "router/memory"    
  - name: "router disk"
    state_topic: "router/disk"    
  - name: "tab cpu temp"
    state_topic: "tab/cpu_temp"

binary_sensor:
  - name: pc disk C state
    state_topic: "pc/DC/state"
    device_class: plug
  - name: pc disk D state
    state_topic: "pc/DD/state"
    device_class: plug

  - name: laptop disk C state
    state_topic: "lap/DC/state"
    device_class: plug
  - name: laptop disk D state
    state_topic: "lap/DD/state"
    device_class: plug
  - name: laptop disk E state
    state_topic: "lap/DE/state"
    device_class: plug
  - name: laptop disk F state
    state_topic: "lap/DF/state"
    device_class: plug
